spring:
  shardingsphere:
    datasource:
      names: m1


      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/course_db?serverTimezone=GMT%2B8
        username: root
        passowrd: root






